import { GetCharactersResults, Characters } from '@/types';
import type { GetStaticProps, NextPage } from 'next';
import Image from 'next/image';
import styles from "../styles/Home.module.css";
import React from 'react';
import Head from 'next/head';
import ImageLoader from '@/ImageLoader';
import Link from 'next/link';

const Home: NextPage<{ characters: Characters[] }> = ({ characters }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {characters.map(character => {
        return (<div key={character.id}>
          <Link href={`characters/${character.id}`}>
              {character.name}
          </Link>
          <Image
            loader={ImageLoader}
            unoptimized
            src={character.image}
            alt={character.name}
            width="200"
            height="200"
          />
        </div>)
      })}
    </div>
  )
}
export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch('https://rickandmortyapi.com/api/character');
  const { results }: GetCharactersResults = await res.json();
  return {
    props: {
      characters: results
    }
  }
}

export default Home